kafka:
  producer:
    brokerUrls: ["localhost:9092"]
    topicName: "test"

  consumer:
    brokerUrls: ["localhost:9092"]
    topicName: "test"
    groupId: "test-app"

  admin:
    brokerUrl: "localhost:9092"
    defaults:
      partitions: 1
      replicas: 1
    createTopics: false
    topics:
      test: "test:1:3" # topic name: test, partitions: 1, replicas: 1
